"""Initial database schema

Revision ID: de3b9f4b3a7d
Revises: 
Create Date: 2026-02-15 21:24:34.528219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3b9f4b3a7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('scoring_settings', sa.JSON(), nullable=True),
    sa.Column('roster_positions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('team', sa.String(length=10), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('injury_status', sa.String(length=50), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('num_divisions', sa.Integer(), nullable=True),
    sa.Column('playoff_structure', sa.JSON(), nullable=True),
    sa.Column('regular_season_weeks', sa.Integer(), nullable=True),
    sa.Column('playoff_weeks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('draft_order', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('points_for', sa.Integer(), nullable=True),
    sa.Column('points_against', sa.Integer(), nullable=True),
    sa.Column('players', sa.JSON(), nullable=True),
    sa.Column('starters', sa.JSON(), nullable=True),
    sa.Column('reserve', sa.JSON(), nullable=True),
    sa.Column('taxi', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_awards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('award_type', sa.String(length=50), nullable=False),
    sa.Column('award_detail', sa.String(length=100), nullable=True),
    sa.Column('roster_id', sa.Integer(), nullable=True),
    sa.Column('final_record', sa.String(length=20), nullable=True),
    sa.Column('points_for', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('roster_ids', sa.JSON(), nullable=True),
    sa.Column('players', sa.JSON(), nullable=True),
    sa.Column('picks', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=50), nullable=False),
    sa.Column('pick_no', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_in_round', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.String(length=50), nullable=True),
    sa.Column('pick_metadata', sa.JSON(), nullable=True),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=True),
    sa.Column('home_roster_id', sa.Integer(), nullable=False),
    sa.Column('home_points', sa.Float(), nullable=True),
    sa.Column('home_starters', sa.String(length=500), nullable=True),
    sa.Column('away_roster_id', sa.Integer(), nullable=False),
    sa.Column('away_points', sa.Float(), nullable=True),
    sa.Column('away_starters', sa.String(length=500), nullable=True),
    sa.Column('winner_roster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_roster_id'], ['rosters.id'], ),
    sa.ForeignKeyConstraint(['home_roster_id'], ['rosters.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['winner_roster_id'], ['rosters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchups')
    op.drop_table('draft_picks')
    op.drop_table('transactions')
    op.drop_table('season_awards')
    op.drop_table('rosters')
    op.drop_table('drafts')
    op.drop_table('seasons')
    op.drop_table('users')
    op.drop_table('players')
    op.drop_table('leagues')
    # ### end Alembic commands ###
